name: Workflow-CI/CD

on:
  push:
    branches:
      - main


jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: test
    container:
      image: node
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: ./to-do-app

      - name: Build website
        run: npm run build
        working-directory: ./to-do-app

      - name: Build website
        run: npm run build
        working-directory: ./to-do-app

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: to-do-app/dist/
          server-dir: public_html/todo/test/

      - name: Install TestCafe
        run: npm install -g testcafe


      - name: Update APT
        run: apt-get update

      - name: Install Chromium
        run: apt-get install -y chromium

      - name: Run TestCafe tests
        run: testcafe chromium:headless src/test-cafe-tests.js
        working-directory: ./to-do-app

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: to-do-app/dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: FTP deploy to Live
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER_LIVE }}
          username: ${{ secrets.FTP_USERNAME_LIVE }}
          password: ${{ secrets.FTP_PASSWORD_LIVE }}
          local-dir: dist/
          server-dir: public_html/todo/live/
